project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1 - DataVis with ggplot2"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2 - Beyond ggplot2 Fundamentals"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3 - Interactive Data Visualisation"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4 - Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.html"
        - text: "Hands-on Exercise 4 - Visualising Uncertainty"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.html"
        - text: "Hands-on Exercise 4 - Building Funnel Plot with R"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.html"
        - text: "Hands-on Exercise 5 - Building Ternary Plot with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_01.html"
        - text: "Hands-on Exercise 5 - Visualising Correlation Matrices with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_02.html"
        - text: "Hands-on Exercise 5 -Building Heatmap for Visualising and Analysing Multivariate Data"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_03.html"
        - text: "Hands-on Exercise 5 - Building Parallel Coordinates Plot with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_04.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 1"
          href: "Inclass_Ex/Inclass_Ex01/Inclass_Ex01.html"
        - text: "In-class Exercise 2"
          href: "Inclass_Ex/Inclass_Ex02/Inclass_Ex02.html"
        - text: "In-class Exercise 3"
          href: "Inclass_Ex/Inclass_Ex03/Inclass_Ex03.html"
        - text: "In-class Exercise 4"
          href: "Inclass_Ex/Inclass_Ex04/Inclass_Ex04.html"
        - text: "In-class Exercise 5"
          href: "Inclass_Ex/Inclass_Ex05/Inclass_Ex05.html"
        - text: "In-class Exercise 6"
          href: "Inclass_Ex/Inclass_Ex06/Inclass_Ex06.html"
        - text: "In-class Exercise 7"
          href: "Inclass_Ex/Inclass_Ex07/Inclass_Ex07.html"
        - text: "In-class Exercise 8"
          href: "Inclass_Ex/Inclass_Ex08/Inclass_Ex08.html"
        - text: "In-class Exercise 9"
          href: "Inclass_Ex/Inclass_Ex09/Inclass_Ex09.html"
        - text: "In-class Exercise 10"
          href: "Inclass_Ex/Inclass_Ex10/Inclass_Ex10.html"
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Takehome_Ex/Takehome_Ex01/Takehome_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Takehome_Ex/Takehome_Ex02/Takehome_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

